### ISSUE TITLE
Stop times only between 12am-4am?

### ISSUE THREAD

**Issue by BenoitDuffez** [sakayph/gtfs#1]
I tried to use the data in this feed, however it doesn't seem that there is data after around 4am. Is it normal?

**Comment by thatsmydoing** [comment]
The stop times are frequency-based. If you check `frequencies.txt`, that's where the actual running times are defined. The times you see in `stop_times.txt` are just relative to when they start.

For example, in `frequencies.txt`, 880815 is defined as between 5:00AM to 7:00AM, so the 00:00:00 in `stop_times.txt` means 5:00AM, 00:03:00 means 5:03AM and so on. It also repeats based on `headway_secs`, in this example 480 seconds or 8 minutes. So 00:00:00 means there will be pickups at the first stop on 5:00AM, 5:08AM, 5:16AM ... until 7:00AM.

You can check the spec for more information https://developers.google.com/transit/gtfs/reference?hl=en#frequenciestxt

If you're using OpenTripPlanner, it should already handle this for you.

**Comment by BenoitDuffez** [comment]
Thanks a lot for the quick and detailed answer.
Cheers
